Repository Lambda-School-Labs/Labs25-Bridges_to_Prosperity-TeamA-fe, pull requests merged in 2020-08, with the labels that each got.

#3 Setup/redux and route boilerplate
  package-lock.json
  package.json
  src/__tests__/Home.test.js
  src/__tests__/RenderExampleListPage.test.js
  src/__tests__/RenderHomePage.test.js
  src/components/pages/Home/HomeContainer.js
  src/components/pages/Home/index.js
  src/components/pages/Home/styles.less
  src/components/pages/Registration/RegistrationContainer.js
  src/components/pages/Registration/index.js
  src/index.js
  src/state/actions/counter.js
  src/state/actions/index.js
  src/state/contexts/index.js
  src/state/index.js
  src/state/reducers/counter.js
  src/state/reducers/index.js
Labels: documentation, enhancement

#8 Home map page/james carpino
  package-lock.json
  package.json
  src/components/pages/Home/HomeContainer.js
  src/components/pages/Home/Mapbox.js
  src/components/pages/Home/styles.less
Labels: enhancement

#14 Enhancement/npm scripts
  package-lock.json
  package.json
Labels: documentation, enhancement

#13 added tooltip to bridge markers to display bridge site name and implemented smooth zoom in
  src/components/pages/Home/Mapbox.js
Labels: enhancement

#17 Map menu map search/james carpino
  src/components/pages/Home/HomeContainer.js
  src/components/pages/Home/MapMenu.js
  src/components/pages/Home/MapSearchBar.js
Labels: enhancement

#18 Search filter/james carpino
  src/components/pages/Home/MapMenu.js
  src/components/pages/Home/MapSearchBar.js
  src/components/pages/Home/Mapbox.js
  src/state/actions/index.js
  src/state/actions/searchLocation.js
  src/state/index.js
  src/state/reducers/searchLocation.js
Labels: enhancement

#19 Feature/add and edit bridge form/devin
  package-lock.json
  package.json
  src/components/common/BridgeForm/BridgeFormAdd.js
  src/components/common/BridgeForm/BridgeFormContainer.js
  src/components/common/BridgeForm/BridgeFormEdit.js
  src/components/common/BridgeForm/BridgeSite.js
  src/components/common/BridgeForm/BridgeSiteList.js
  src/components/common/BridgeForm/index.js
  src/components/pages/Test/index.js
  src/index.js
  src/state/actions/bridgeSites.js
  src/state/actions/index.js
  src/state/index.js
  src/state/reducers/bridgeSites.js
Labels: enhancement

#30 Documentation and testing
  EXAMPLE_README.md
  README.md
  src/__tests__/Home.test.js
  src/components/pages/Home/HomeContainer.js
  src/components/pages/Home/MapMenu.js
  src/components/pages/Home/styles.less
Labels: documentation, enhancement

#28 Sign in and sign out links conditionally appear depending on user's logged in status
  src/__tests__/Home.test.js
  src/components/common/BridgeForm/BridgeFormAdd.js
  src/components/common/BridgeForm/BridgeFormContainer.js
  src/components/common/BridgeForm/BridgeFormEdit.js
  src/components/common/BridgeForm/BridgeSite.js
  src/components/common/BridgeForm/BridgeSiteList.js
  src/components/pages/Home/BridgeList.js
  src/components/pages/Home/MapMenu.js
  src/components/pages/Home/styles.less
Labels: enhancement

#33 Feat/delete bridge option/devin
  src/components/common/BridgeForm/BridgeFormContainer.js
  src/components/common/BridgeForm/BridgeFormEdit.js
  src/components/common/BridgeForm/styles.less
Labels: enhancement

#35 Search filter/james carpino
  .env.sample
  src/components/pages/Home/HomeContainer.js
  src/components/pages/Home/MapMenu.js
  src/components/pages/Home/MapSearchBar.js
  src/state/actions/bridgeSites.js
  src/state/actions/searchLocation.js
  src/state/reducers/bridgeSitesReducer.js
Labels: enhancement

#36 Feat/integrate forms/devin
  src/components/common/BridgeForm/BridgeFormAdd.js
  src/components/common/BridgeForm/BridgeFormContainer.js
  src/components/common/BridgeForm/BridgeFormEdit.js
  src/components/common/BridgeForm/styles.less
  src/components/pages/BridgeForms.js/index.js
  src/components/pages/Home/BridgeList.js
  src/components/pages/Home/HomeContainer.js
  src/components/pages/Home/MapMenu.js
  src/components/pages/Test/index.js
  src/index.js
  src/state/actions/bridgeSites.js
  src/utils/axiosWithAuth.js
Labels: enhancement

#38 Implemented some responsiveness to map view
  src/components/pages/Home/HomeContainer.js
  src/components/pages/Home/MapMenu.js
  src/components/pages/Home/MapSearchBar.js
  src/components/pages/Home/Mapbox.js
  src/components/pages/Home/styles.less
Labels: enhancement

#40 Map style options/james
  package-lock.json
  package.json
  src/components/pages/Home/BridgeList.js
  src/components/pages/Home/HomeContainer.js
  src/components/pages/Home/MapMenu.js
  src/components/pages/Home/MapSearchBar.js
  src/components/pages/Home/Mapbox.js
  src/components/pages/Home/Themes.js
  src/components/pages/Home/assets/pinMarker.png
  src/components/pages/Home/styles.less
Labels: enhancement

#47 Bug/fix zoom/devin james
  src/components/pages/Home/HomeContainer.js
  src/components/pages/Home/MapMenu.js
Labels: bug

#46 Map bug fixed - everthing was wrapped in menu lol
  src/components/pages/Home/HomeContainer.js
Labels: bug

#49 Used function to check menu toggle on marker press
  src/components/pages/Home/HomeContainer.js
  src/components/pages/Home/Mapbox.js
Labels: enhancement
